# Generated by Django 4.2.3 on 2023-07-20 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador')),
                ('dataRegistre', models.DateTimeField(auto_now_add=True, verbose_name='Data registre')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrenament', to='api.model', verbose_name='Model')),
            ],
        ),
    ]
