# Generated by Django 4.2.3 on 2023-07-21 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_entrenament'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metrica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('nomTecnic', models.CharField(max_length=100, verbose_name='Nom tècnic')),
                ('fase', models.CharField(choices=[('T', 'Entrenament'), ('I', 'Inferència')], max_length=5, verbose_name='Fase')),
                ('pes', models.FloatField(blank=True, null=True, verbose_name='Pes')),
                ('influencia', models.CharField(choices=[('P', 'Positiva'), ('N', 'Negativa')], max_length=5, verbose_name='Influència')),
                ('descripcio', models.CharField(max_length=1000, verbose_name='Descripcio')),
                ('limits', models.CharField(max_length=1000, verbose_name='Límits')),
            ],
        ),
        migrations.AlterField(
            model_name='entrenament',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrenaments', to='api.model', verbose_name='Model'),
        ),
        migrations.CreateModel(
            name='ResultatEntrenament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('entrenament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='api.model', verbose_name='Entrenament')),
                ('metrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='api.metrica', verbose_name='Mètrica')),
            ],
        ),
    ]
