# Generated by Django 4.2.3 on 2023-07-21 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_metrica_alter_entrenament_model_resultatentrenament'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metrica',
            options={'verbose_name_plural': 'Mètriques'},
        ),
    ]
