# Generated by Django 4.2.3 on 2023-07-31 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_qualificacio_interval'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qualificacio',
            options={'verbose_name_plural': 'Qualificacions'},
        ),
    ]
