# Generated by Django 4.2.3 on 2023-07-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_qualificacio_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrica',
            name='unitat',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Unitat'),
        ),
    ]
