# Generated by Django 4.2.3 on 2023-07-31 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_qualificacio_ordre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metrica',
            name='limits',
        ),
    ]
