# Generated by Django 4.2.3 on 2023-10-25 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_infoaddicional_valorinfoentrenament'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorInfoInferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=10000, verbose_name='Valor')),
                ('inferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informacionsInferencia', to='api.inferencia', verbose_name='Inferència')),
                ('infoAddicional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informacionsInferencia', to='api.infoaddicional', verbose_name='Informació')),
            ],
        ),
    ]
