# Generated by Django 4.2.3 on 2023-10-25 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_valorinfoinferencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valorinfoinferencia',
            options={'verbose_name_plural': 'Valor info inferències'},
        ),
    ]
