# Generated by Django 4.2.3 on 2023-12-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_metrica_calcul_metrica_recomanacions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='einacalcul',
            name='descripcio',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Descripció'),
        ),
    ]
