# Generated by Django 4.2.3 on 2023-12-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_resultatentrenament_valor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimaSincronitzacio', models.DateTimeField(verbose_name='Última sincronització')),
            ],
            options={
                'verbose_name_plural': 'Configuracions',
            },
        ),
    ]
