# Generated by Django 4.2.3 on 2025-01-10 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_configuracio'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Optimization Technique')),
            ],
            options={
                'verbose_name': 'Optimization Technique',
                'verbose_name_plural': 'Optimization Techniques',
            },
        ),
        migrations.CreateModel(
            name='ROIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique_param', models.CharField(blank=True, max_length=255, null=True, verbose_name='Technique Parameters')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Registration Date')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Country of Deployment')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roi_analyses', to='api.model', verbose_name='Model')),
                ('optimization_technique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.optimizationtechnique', verbose_name='Optimization Technique')),
            ],
            options={
                'verbose_name': 'ROI Analysis',
                'verbose_name_plural': 'ROI Analyses',
            },
        ),
        migrations.CreateModel(
            name='ROICostMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('optimization', 'OptimizationCosts'), ('original', 'OriginalInferenceCosts'), ('new', 'NewInferenceCosts')], max_length=50, verbose_name='Cost Type')),
                ('total_packs', models.IntegerField(verbose_name='Total Packs')),
                ('cost_per_pack', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost per Pack')),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taxes')),
                ('num_inferences', models.IntegerField(blank=True, null=True, verbose_name='Number of Inferences')),
                ('roi_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roi_cost_metrics', to='api.roianalysis', verbose_name='ROI Analysis')),
            ],
            options={
                'verbose_name': 'ROI Cost Metrics',
                'verbose_name_plural': 'ROI Cost Metrics',
            },
        ),
    ]
