# Generated by Django 4.2.3 on 2025-04-22 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_techniqueparameter_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GAISSAROIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Registration Date')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Country of Deployment')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaissa_roi_analyses', to='api.model', verbose_name='Model')),
                ('optimization_technique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.optimizationtechnique', verbose_name='Optimization Technique')),
                ('technique_parameter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.techniqueparameter', verbose_name='Technique Parameter')),
            ],
            options={
                'verbose_name': 'GAISSA ROI Analysis',
                'verbose_name_plural': 'GAISSA ROI Analyses',
            },
        ),
        migrations.CreateModel(
            name='GAISSAROICostMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('optimization', 'OptimizationCosts'), ('original', 'OriginalInferenceCosts'), ('new', 'NewInferenceCosts')], max_length=50, verbose_name='Cost Type')),
                ('total_packs', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Packs')),
                ('cost_per_pack', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost per Pack')),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taxes')),
                ('num_inferences', models.IntegerField(blank=True, null=True, verbose_name='Number of Inferences')),
                ('gaissa_roi_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaissa_roi_cost_metrics', to='api.gaissaroianalysis', verbose_name='GAISSA ROI Analysis')),
            ],
            options={
                'verbose_name': 'GAISSA ROI Cost Metrics',
                'verbose_name_plural': 'GAISSA ROI Cost Metrics',
            },
        ),
        migrations.RemoveField(
            model_name='roicostmetrics',
            name='roi_analysis',
        ),
        migrations.DeleteModel(
            name='ROIAnalysis',
        ),
        migrations.DeleteModel(
            name='ROICostMetrics',
        ),
    ]
