# Generated by Django 4.2.3 on 2025-04-23 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_gaissaroianalysis_gaissaroicostmetrics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisMetricValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('baselineValue', models.FloatField(verbose_name='Baseline Value')),
            ],
            options={
                'verbose_name': 'Analysis Metric Value',
                'verbose_name_plural': 'Analysis Metric Values',
            },
        ),
        migrations.CreateModel(
            name='ExpectedMetricReduction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expectedReductionValue', models.FloatField(verbose_name='Expected Reduction Value')),
            ],
            options={
                'verbose_name': 'Expected Metric Reduction',
                'verbose_name_plural': 'Expected Metric Reductions',
            },
        ),
        migrations.CreateModel(
            name='MLTactic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tactic Name')),
                ('information', models.TextField(blank=True, null=True, verbose_name='Information')),
            ],
            options={
                'verbose_name': 'ML Tactic',
                'verbose_name_plural': 'ML Tactics',
            },
        ),
        migrations.CreateModel(
            name='ModelArchitecture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Architecture Name')),
                ('information', models.TextField(blank=True, null=True, verbose_name='Information')),
            ],
            options={
                'verbose_name': 'Model Architecture',
                'verbose_name_plural': 'Model Architectures',
            },
        ),
        migrations.CreateModel(
            name='ROIAnalysis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_architecture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roi_analyses', to='api.modelarchitecture', verbose_name='Model Architecture')),
            ],
            options={
                'verbose_name': 'ROI Analysis',
                'verbose_name_plural': 'ROI Analyses',
            },
        ),
        migrations.CreateModel(
            name='ROIMetric',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Metric Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit')),
            ],
            options={
                'verbose_name': 'ROI Metric',
                'verbose_name_plural': 'ROI Metrics',
            },
        ),
        migrations.CreateModel(
            name='TacticParameterOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Parameter Name')),
                ('value', models.CharField(max_length=255, verbose_name='Parameter Value')),
                ('tactic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_options', to='api.mltactic', verbose_name='Tactic')),
            ],
            options={
                'verbose_name': 'Tactic Parameter Option',
                'verbose_name_plural': 'Tactic Parameter Options',
                'unique_together': {('tactic', 'name', 'value')},
            },
        ),
        migrations.CreateModel(
            name='TacticSource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Source Title')),
                ('url', models.URLField(max_length=500, verbose_name='Source URL')),
            ],
            options={
                'verbose_name': 'Tactic Source',
                'verbose_name_plural': 'Tactic Sources',
            },
        ),
        migrations.RemoveField(
            model_name='gaissaroicostmetrics',
            name='gaissa_roi_analysis',
        ),
        migrations.AlterUniqueTogether(
            name='techniqueparameter',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='techniqueparameter',
            name='optimization_technique',
        ),
        migrations.CreateModel(
            name='ROIAnalysisCalculation',
            fields=[
                ('roianalysis_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.roianalysis')),
                ('dateRegistration', models.DateTimeField(auto_now_add=True, verbose_name='Registration Date')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Country of Deployment')),
            ],
            options={
                'verbose_name': 'ROI Analysis Calculation',
                'verbose_name_plural': 'ROI Analysis Calculations',
            },
            bases=('api.roianalysis',),
        ),
        migrations.CreateModel(
            name='ROIAnalysisResearch',
            fields=[
                ('roianalysis_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.roianalysis')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roi_analysis_researches', to='api.tacticsource', verbose_name='Source')),
            ],
            options={
                'verbose_name': 'ROI Analysis Research',
                'verbose_name_plural': 'ROI Analysis Researches',
            },
            bases=('api.roianalysis',),
        ),
        migrations.DeleteModel(
            name='GAISSAROIAnalysis',
        ),
        migrations.DeleteModel(
            name='GAISSAROICostMetrics',
        ),
        migrations.DeleteModel(
            name='OptimizationTechnique',
        ),
        migrations.DeleteModel(
            name='TechniqueParameter',
        ),
        migrations.AddField(
            model_name='roianalysis',
            name='tactic_parameter_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roi_analyses', to='api.tacticparameteroption', verbose_name='Tactic Parameter Option'),
        ),
        migrations.AddField(
            model_name='mltactic',
            name='sources',
            field=models.ManyToManyField(related_name='tactics', to='api.tacticsource', verbose_name='Sources'),
        ),
        migrations.AddField(
            model_name='expectedmetricreduction',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.roimetric', verbose_name='ROI Metric'),
        ),
        migrations.AddField(
            model_name='expectedmetricreduction',
            name='model_architecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.modelarchitecture', verbose_name='Model Architecture'),
        ),
        migrations.AddField(
            model_name='expectedmetricreduction',
            name='tactic_parameter_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tacticparameteroption', verbose_name='Tactic Parameter Option'),
        ),
        migrations.AddField(
            model_name='analysismetricvalue',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_values', to='api.roianalysis', verbose_name='ROI Analysis'),
        ),
        migrations.AddField(
            model_name='analysismetricvalue',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_values', to='api.roimetric', verbose_name='ROI Metric'),
        ),
        migrations.AlterUniqueTogether(
            name='expectedmetricreduction',
            unique_together={('model_architecture', 'tactic_parameter_option', 'metric')},
        ),
        migrations.AlterUniqueTogether(
            name='analysismetricvalue',
            unique_together={('analysis', 'metric')},
        ),
    ]
