# Generated by Django 4.2.3 on 2025-04-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_mltactic_compatible_architectures'),
    ]

    operations = [
        migrations.AddField(
            model_name='mltactic',
            name='applicable_metrics',
            field=models.ManyToManyField(blank=True, related_name='applicable_tactics', to='api.roimetric', verbose_name='Applicable Metrics'),
        ),
    ]
