# Generated by Django 4.2.3 on 2025-04-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_mltactic_applicable_metrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roianalysiscalculation',
            name='country',
            field=models.CharField(default='Italia', max_length=255, verbose_name='Country of Deployment'),
            preserve_default=False,
        ),
    ]
