# Generated by Django 4.2.21 on 2025-05-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_roimetric_max_value_roimetric_min_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracio',
            name='gaissa_label_enabled',
            field=models.BooleanField(default=True, verbose_name='GAISSALabel Enabled'),
        ),
        migrations.AddField(
            model_name='configuracio',
            name='gaissa_roi_analyzer_enabled',
            field=models.BooleanField(default=True, verbose_name='GAISSA ROI Analyzer Enabled'),
        ),
    ]
