# Generated by Django 4.2.21 on 2025-05-27 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_configuracio_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Country Name')),
                ('country_code', models.CharField(max_length=2, unique=True, verbose_name='Country Code')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarbonIntensity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carbon_intensity', models.FloatField(verbose_name='Carbon Intensity (kgCO2/kWh)')),
                ('data_year', models.IntegerField(blank=True, null=True, verbose_name='Data Year')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_intensities', to='api.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Country Carbon Intensity',
                'verbose_name_plural': 'Country Carbon Intensities',
                'ordering': ['country'],
                'unique_together': {('country', 'data_year')},
            },
        ),
    ]
