# Generated by Django 4.2.21 on 2025-05-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_country_carbonintensity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=models.CharField(max_length=5, unique=True, verbose_name='Country Code'),
        ),
    ]
