# Generated by Django 4.2.21 on 2025-05-28 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_country_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roianalysiscalculation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roi_analysis_calculations', to='api.country', verbose_name='Country of Deployment'),
        ),
    ]
