# Generated by Django 4.2.21 on 2025-05-29 15:09

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_roianalysiscalculation_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roianalysiscalculation',
            name='country',
        ),
        migrations.AddField(
            model_name='roianalysis',
            name='country',
            field=models.ForeignKey(default=api.models.get_default_country, on_delete=django.db.models.deletion.PROTECT, related_name='roi_analyses', to='api.country', verbose_name='Country of Deployment'),
        ),
    ]
