# Generated by Django 4.2.3 on 2023-07-21 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_metrica_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultatentrenament',
            name='entrenament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='api.entrenament', verbose_name='Entrenament'),
        ),
    ]
