# Generated by Django 4.2.3 on 2023-07-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_metrica_descripcio_alter_metrica_limits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metrica',
            name='nomTecnic',
        ),
        migrations.AlterField(
            model_name='metrica',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Identificador'),
        ),
    ]
