# Generated by Django 4.2.3 on 2023-07-31 12:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_metrica_descripcio_alter_metrica_limits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualificacio',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Identificador')),
                ('color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#([A-Fa-f0-9]{6})$')], verbose_name='Color')),
            ],
        ),
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador')),
                ('limitInferior', models.FloatField(verbose_name='Límit inferior')),
                ('limitSuperior', models.FloatField(verbose_name='Límit superior')),
                ('imatge', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imatge')),
                ('metrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='api.metrica', verbose_name='Mètrica')),
                ('qualificacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='api.qualificacio', verbose_name='Qualificació')),
            ],
        ),
    ]
