# Generated by Django 4.2.3 on 2023-07-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_metrica_unitat'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualificacio',
            name='ordre',
            field=models.IntegerField(default=0, verbose_name='Ordre'),
            preserve_default=False,
        ),
    ]
