# Generated by Django 4.2.3 on 2023-09-16 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_model_informacio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inferencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador')),
                ('dataRegistre', models.DateTimeField(auto_now_add=True, verbose_name='Data registre')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inferencies', to='api.model', verbose_name='Model')),
            ],
            options={
                'verbose_name_plural': 'Inferències',
            },
        ),
        migrations.AlterField(
            model_name='resultatentrenament',
            name='entrenament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultatsEntrenament', to='api.entrenament', verbose_name='Entrenament'),
        ),
        migrations.AlterField(
            model_name='resultatentrenament',
            name='metrica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultatsEntrenament', to='api.metrica', verbose_name='Mètrica'),
        ),
        migrations.CreateModel(
            name='ResultatInferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('inferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultatsInferencia', to='api.inferencia', verbose_name='Inferència')),
                ('metrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultatsInferencia', to='api.metrica', verbose_name='Mètrica')),
            ],
            options={
                'verbose_name_plural': 'Resultat Inferències',
            },
        ),
    ]
