# Generated by Django 4.2.3 on 2023-12-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_administrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrica',
            name='calcul',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Com es calcula'),
        ),
        migrations.AddField(
            model_name='metrica',
            name='recomanacions',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Recomanacions'),
        ),
    ]
