# Generated by Django 4.2.3 on 2023-12-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_einacalcul_descripcio'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='autor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Autor/a'),
        ),
    ]
