# Generated by Django 4.2.3 on 2025-01-16 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_optimizationtechnique_roianalysis_roicostmetrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roianalysis',
            name='technique_param',
        ),
    ]
