# Generated by Django 4.2.3 on 2025-01-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_roianalysis_technique_param'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roicostmetrics',
            name='total_packs',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Packs'),
        ),
    ]
