# Generated by Django 4.2.3 on 2025-01-28 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_roicostmetrics_total_packs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roianalysis',
            name='optimization_technique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.optimizationtechnique', verbose_name='Optimization Technique'),
        ),
        migrations.CreateModel(
            name='TechniqueParameter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Parameter Name')),
                ('optimization_technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technique_parameters', to='api.optimizationtechnique')),
            ],
            options={
                'verbose_name': 'Technique Parameter',
                'verbose_name_plural': 'Technique Parameters',
                'unique_together': {('optimization_technique', 'name')},
            },
        ),
        migrations.AddField(
            model_name='roianalysis',
            name='technique_parameter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.techniqueparameter', verbose_name='Technique Parameter'),
        ),
    ]
