# Generated by Django 4.2.3 on 2025-01-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_roianalysis_optimization_technique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techniqueparameter',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Parameter Name'),
        ),
    ]
