# Generated by Django 4.2.3 on 2025-01-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_techniqueparameter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techniqueparameter',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Parameter Name'),
        ),
    ]
