# Generated by Django 4.2.3 on 2025-04-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_analysismetricvalue_expectedmetricreduction_mltactic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mltactic',
            name='compatible_architectures',
            field=models.ManyToManyField(blank=True, related_name='compatible_tactics', to='api.modelarchitecture', verbose_name='Compatible Architectures'),
        ),
    ]
