# Generated by Django 4.2.3 on 2025-04-30 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_roianalysiscalculation_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyAnalysisMetricValue',
            fields=[
                ('analysismetricvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.analysismetricvalue')),
                ('energy_cost_rate', models.DecimalField(decimal_places=4, help_text='The cost per kilowatt-hour of energy in €', max_digits=10, verbose_name='Energy Cost Rate (€/kWh)')),
                ('implementation_cost', models.DecimalField(decimal_places=2, help_text='Additional costs for implementing this energy optimization tactic in €', max_digits=10, verbose_name='Implementation Costs (€)')),
            ],
            options={
                'verbose_name': 'Energy Metric Analysis Value',
                'verbose_name_plural': 'Energy Metric Analysis Values',
            },
            bases=('api.analysismetricvalue',),
        ),
        migrations.AddField(
            model_name='roimetric',
            name='is_energy_related',
            field=models.BooleanField(default=False, verbose_name='Is Energy Related'),
        ),
    ]
