# Generated by Django 4.2.3 on 2025-05-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_energyanalysismetricvalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roimetric',
            name='higher_is_better',
            field=models.BooleanField(default=False, verbose_name='Higher is better'),
        ),
    ]
