# Generated by Django 4.2.3 on 2025-05-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_roimetric_higher_is_better'),
    ]

    operations = [
        migrations.AddField(
            model_name='roimetric',
            name='max_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Maximum Value'),
        ),
        migrations.AddField(
            model_name='roimetric',
            name='min_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Minimum Value'),
        ),
    ]
