# Generated by Django 4.2.21 on 2025-05-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_configuracio_gaissa_label_enabled_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracio',
            options={'verbose_name': 'Configuration', 'verbose_name_plural': 'Configurations'},
        ),
        migrations.AlterField(
            model_name='configuracio',
            name='ultimaSincronitzacio',
            field=models.DateTimeField(verbose_name='Last GAISSA Label Model Synchronization'),
        ),
    ]
