# Generated by Django 4.2.21 on 2025-06-08 11:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EinaCalcul',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('descripcio', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Descripció')),
            ],
            options={
                'verbose_name_plural': 'Eines càlcul',
            },
        ),
        migrations.CreateModel(
            name='Entrenament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador')),
                ('dataRegistre', models.DateTimeField(auto_now_add=True, verbose_name='Data registre')),
            ],
        ),
        migrations.CreateModel(
            name='Inferencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador')),
                ('dataRegistre', models.DateTimeField(auto_now_add=True, verbose_name='Data registre')),
            ],
            options={
                'verbose_name_plural': 'Inferències',
            },
        ),
        migrations.CreateModel(
            name='InfoAddicional',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Identificador')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('fase', models.CharField(choices=[('T', 'Entrenament'), ('I', 'Inferència')], max_length=5, verbose_name='Fase')),
                ('descripcio', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Descripcio')),
                ('opcions', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Opcions')),
            ],
        ),
        migrations.CreateModel(
            name='Metrica',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Identificador')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('fase', models.CharField(choices=[('T', 'Entrenament'), ('I', 'Inferència')], max_length=5, verbose_name='Fase')),
                ('pes', models.FloatField(blank=True, null=True, verbose_name='Pes')),
                ('unitat', models.CharField(blank=True, max_length=5, null=True, verbose_name='Unitat')),
                ('influencia', models.CharField(choices=[('P', 'Positiva'), ('N', 'Negativa')], max_length=5, verbose_name='Influència')),
                ('descripcio', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Descripcio')),
                ('calcul', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Com es calcula')),
                ('recomanacions', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Recomanacions')),
            ],
            options={
                'verbose_name_plural': 'Mètriques',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('autor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Autor/a')),
                ('informacio', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Informació')),
                ('dataCreacio', models.DateTimeField(auto_now_add=True, verbose_name='Data creació')),
            ],
        ),
        migrations.CreateModel(
            name='Qualificacio',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Identificador')),
                ('color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#([A-Fa-f0-9]{6})$')], verbose_name='Color')),
                ('ordre', models.IntegerField(verbose_name='Ordre')),
            ],
            options={
                'verbose_name_plural': 'Qualificacions',
            },
        ),
        migrations.CreateModel(
            name='ValorInfoInferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=10000, verbose_name='Valor')),
                ('inferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informacionsInferencia', to='gaissalabel.inferencia', verbose_name='Inferència')),
                ('infoAddicional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informacionsInferencia', to='gaissalabel.infoaddicional', verbose_name='Informació')),
            ],
            options={
                'verbose_name_plural': 'Valor info inferències',
            },
        ),
        migrations.CreateModel(
            name='ValorInfoEntrenament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=10000, verbose_name='Valor')),
                ('entrenament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informacionsEntrenament', to='gaissalabel.entrenament', verbose_name='Entrenament')),
                ('infoAddicional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informacionsEntrenament', to='gaissalabel.infoaddicional', verbose_name='Informació')),
            ],
        ),
        migrations.CreateModel(
            name='TransformacioMetrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=100, verbose_name='Valor')),
                ('eina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformacionsMetriques', to='gaissalabel.einacalcul', verbose_name='Eina càlcul')),
                ('metrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformacions', to='gaissalabel.metrica', verbose_name='Mètrica')),
            ],
            options={
                'verbose_name_plural': 'Transformació Mètriques',
            },
        ),
        migrations.CreateModel(
            name='TransformacioInformacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=100, verbose_name='Valor')),
                ('eina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformacionsInformacions', to='gaissalabel.einacalcul', verbose_name='Eina càlcul')),
                ('informacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformacions', to='gaissalabel.infoaddicional', verbose_name='Informació addicional')),
            ],
            options={
                'verbose_name_plural': 'Transformació Informacions',
            },
        ),
        migrations.CreateModel(
            name='ResultatInferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(blank=True, null=True, verbose_name='Valor')),
                ('inferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultatsInferencia', to='gaissalabel.inferencia', verbose_name='Inferència')),
                ('metrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultatsInferencia', to='gaissalabel.metrica', verbose_name='Mètrica')),
            ],
            options={
                'verbose_name_plural': 'Resultat Inferències',
            },
        ),
        migrations.CreateModel(
            name='ResultatEntrenament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(blank=True, null=True, verbose_name='Valor')),
                ('entrenament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultatsEntrenament', to='gaissalabel.entrenament', verbose_name='Entrenament')),
                ('metrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultatsEntrenament', to='gaissalabel.metrica', verbose_name='Mètrica')),
            ],
        ),
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador')),
                ('limitSuperior', models.FloatField(verbose_name='Límit superior')),
                ('limitInferior', models.FloatField(verbose_name='Límit inferior')),
                ('imatge', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imatge')),
                ('metrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='gaissalabel.metrica', verbose_name='Mètrica')),
                ('qualificacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='gaissalabel.qualificacio', verbose_name='Qualificació')),
            ],
        ),
        migrations.AddField(
            model_name='inferencia',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inferencies', to='gaissalabel.model', verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='entrenament',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrenaments', to='gaissalabel.model', verbose_name='Model'),
        ),
    ]
