# Generated by Django 4.2.23 on 2025-06-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaissa_roi_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyanalysismetricvalue',
            name='energy_cost_rate',
            field=models.DecimalField(decimal_places=6, help_text='The cost per kilowatt-hour of energy in €', max_digits=10, verbose_name='Energy Cost Rate (€/kWh)'),
        ),
        migrations.AlterField(
            model_name='energyanalysismetricvalue',
            name='implementation_cost',
            field=models.DecimalField(decimal_places=10, help_text='Additional costs for implementing this energy optimization tactic in €', max_digits=14, verbose_name='Implementation Costs (€)'),
        ),
    ]
