# Generated by Django 4.2.25 on 2025-10-26 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "gaissa_roi_analyzer",
            "0002_alter_energyanalysismetricvalue_energy_cost_rate_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MLPipelineStage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Stage Name"
                    ),
                ),
            ],
            options={
                "verbose_name": "ML Pipeline Stage",
                "verbose_name_plural": "ML Pipeline Stages",
            },
        ),
        migrations.AddField(
            model_name="mltactic",
            name="pipeline_stage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tactics",
                to="gaissa_roi_analyzer.mlpipelinestage",
                verbose_name="Pipeline Stage",
            ),
        ),
    ]
