# Generated by Django 4.2.25 on 2025-10-28 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gaissa_roi_analyzer", "0003_mlpipelinestage_mltactic_pipeline_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mltactic",
            name="pipeline_stage",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tactics",
                to="gaissa_roi_analyzer.mlpipelinestage",
                verbose_name="Pipeline Stage",
            ),
            preserve_default=False,
        ),
    ]
