// Mock data for trainings, inferencies, metriques and models

export const mockTrainingResponse = {
    data: {
        energy_label: "mockBase64",
        color: "#639b30",
        resultats: {
            size_efficency: {
                value: 266551.57,
                qualificacio: "A",
                color: "#639b30",
                unit: "B"
            },
            performance_score: {
                value: 0.7,
                qualificacio: "C", 
                color: "#FFA500"
            }
        },
        infoEntrenament: {
            model: 1,
            id: 1,
            dataRegistre: "2023-11-21T17:01:34.781082Z",
            resultats: {
                co2_eq_emissions: 0.2,
                size_efficency: 0.3,
                datasets_size_efficency: 266551.57,
                downloads: 3456,
                performance_score: 0.7
            },
            infoAddicional: {}
        }
    },
    status: 200,
    statusText: "OK",
    headers: {
        "content-length": "333739",
        "content-type": "application/json"
    }
};

export const mockModelResponse = {
    data: {
        id: 1,
        nom: "GPT-2",
        autor: null,
        informacio: "GPT-2 is a transformers model...",
        dataCreacio: "2023-11-21T16:59:36.312175Z"
    },
    status: 200,
    statusText: "OK",
    headers: {
        "content-length": "497",
        "content-type": "application/json"
    }
};

export const mockMetriquesResponse = {
    data: [
        {
            "id": "size_efficency",
            "intervals": [
                {
                    "qualificacio": "A",
                    "limitSuperior": 100000000000000000000,
                    "limitInferior": 621520.4974319822
                },
                {
                    "qualificacio": "B",
                    "limitSuperior": 621520.4974319822,
                    "limitInferior": 135784.50299839783
                },
                {
                    "qualificacio": "C",
                    "limitSuperior": 135784.50299839783,
                    "limitInferior": 40312.23486482583
                },
                {
                    "qualificacio": "D",
                    "limitSuperior": 40312.23486482583,
                    "limitInferior": 10344.486801846353
                },
                {
                    "qualificacio": "E",
                    "limitSuperior": 10344.486801846353,
                    "limitInferior": 0
                }
            ],
            "nom": "Size efficiency",
            "fase": "T",
            "pes": 0.15,
            "unitat": "B",
            "influencia": "P",
            "descripcio": "The size efficiency is obtained as the ratio of the model size and the CO2 emissions generated by this model. Therefore, a higher size efficiency means that the model can achieve low emissions even with a high model complexity. Note that by size efficiency, we are referring to the total number of learned variables per its total size.",
            "calcul": "Divide the model size (i.e. the number of parameters) by the CO2 emissions result.",
            "recomanacions": "Model Pruning: Use model pruning techniques to remove unnecessary parameters, reducing model size without compromising performance.;Knowledge Distillation: Apply knowledge distillation to train smaller models that are as effective as larger ones.;Efficient Neural Network Architectures: Employ efficient neural network architectures like MobileNets or EfficientNets that are designed for lower energy consumption.;Other Model Optimizations"
        },
        {
            "id": "performance_score",
            "intervals": [
                {
                    "qualificacio": "C",
                    "limitSuperior": 1.0863867368274065,
                    "limitInferior": 0.9087507286534131
                },
                {
                    "qualificacio": "D",
                    "limitSuperior": 0.9087507286534131,
                    "limitInferior": 0.5819579813505866
                },
                {
                    "qualificacio": "E",
                    "limitSuperior": 0.5819579813505866,
                    "limitInferior": 0
                },
                {
                    "qualificacio": "A",
                    "limitSuperior": 100000000000000000000,
                    "limitInferior": 1.1745383012572745
                },
                {
                    "qualificacio": "B",
                    "limitSuperior": 1.1745383012572745,
                    "limitInferior": 1.0863867368274065
                }
            ],
            "nom": "Performance score",
            "fase": "T",
            "pes": 0.2,
            "unitat": null,
            "influencia": "P",
            "descripcio": "To evaluate the performance or quality of the model, there are different metrics that help us evaluate such performance. Some examples are accuracy, f1 score or Rouge1, amount others.",
            "calcul": "Indicate the result of the performance score metric that betters suits your problem. You can use F1 score, accuracy or top 3 accuracy, among others.",
            "recomanacions": "Enhanced Algorithm Accuracy: Continuously refine your algorithms for higher accuracy, reducing the need for retraining and thus saving energy.;Adaptive Learning Techniques: Implement adaptive learning techniques that adjust the model's complexity based on the task, conserving energy.;Regular Benchmarking: Regularly benchmark the tool against the latest industry standards to ensure it remains efficient and competitive."
        }
    ],
};